### ISSUE TITLE
添加触发验证有解决思路吗

### ISSUE THREAD

**Issue by 781015928** [SeanClancy84/115downloadRequest#1]
我记得之前添加频率高时会触发人机认证，另外哥们研究过迅雷的添加么，迅雷除了添加磁力其他的都能跑通了

**Comment by SeanClancy84** [comment]
暂时还不会用脚本解决验证码。
实测是每提交大约10-20次左右，就会触发911errcode人机验证，或者更少次（每次提交的任务数量多），必须要管理员手动去115官方微信小程序或者115网页版任意添加一个链接，手动通过人机验证，才能继续使用

没有迅雷云盘，也没有研究过，不过你会wireshark抓包的话，可以自己调试改一下提交任务的模块
